- type: job
  id: OperativeNCSP
  name: job-name-operative
  description: job-description-operative
  playTimeTracker: JobOperativeNCSP
  weight: 14
  startingGear: OperativeGear
  alwaysUseSpawner: true
  requirements:
    - !type:FactionRequirement
      factionID: "TFSC"
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-freeman
  icon: "JobIconSyndieOperative"
  requireAdminNotify: false
  supervisors: job-supervisors-ncsp 
  canBeAntag: false
  access:
  - Command
  - Maintenance
  - SyndicateBasic
  - SyndicateRamzi
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: OperativeGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSyndicateSoldierCyberdawn
    id: OperativePDa
    outerClothing: ClothingOuterArmorKendoBogu
    ears: ClothingHeadsetNCSPCyberdawn
    pocket1: WeaponPistolHKUSP